name: "sha"

on:
  workflow_dispatch:
  

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Go
        run: | 
          curl -LO https://archive.org/download/sjarb_android_6.0r3/android-x86_64-6.0-r3.iso
          
          sha256sum *.iso
        continue-on-error: true
